apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 540700646425.dkr.ecr.us-east-1.amazonaws.com/frontend:188276d
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: frontend-config-map
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config-map
data:
  REACT_APP_MOVIE_API_URL: af53e2d7c842146d6bcf5284bf264f66-1921078887.us-east-1.elb.amazonaws.com
