name: "Deploy to EKS"
description: "Deploy to EKS"

inputs:
    working_directory:
      description: "Path of project"
      required: true
    aws_access_key_id:
      description: "AWS_ACCESS_KEY_ID"
      required: true
    aws_secret_access_key:
      description: "AWS_SECRET_ACCESS_KEY"
      required: true
    aws_session_token:
      description: "AWS_SESSION_TOKEN"
      required: false
    aws_region:
      description: "AWS Region default to us-east-1"
      default: "us-east-1"
      required: false
    cluster_name:
      description: "Cluster name in AWS"
      required: true
runs: 
  using: composite
  steps:
    - name: Install Kubectl - Kustomize
      shell: bash
      run: |
        sudo curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        sudo curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
        sudo mv kustomize /usr/local/bin

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-session-token: ${{ inputs.aws_session_token }}
        aws-region: ${{ inputs.aws_region }}
        output-credentials: true

    - name: Verify AWS Credentials
      shell: bash
      run: |
        echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"

    - name: Debug AWS CLI Configuration
      shell: bash
      run: aws configure list

    - name: Configure Kubectl
      env:
        CLUSTER_NAME: ${{ inputs.cluster_name }}
        AWS_REGION: ${{ inputs.aws_region }}
      shell: bash
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

    - name: Deploy
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        kustomize build ./k8s  | kubectl apply -k ./k8s

