apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  clusterName: cluster
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 540700646425.dkr.ecr.us-east-1.amazonaws.com/backend:eb1a5ff
          ports:
            - containerPort: 5000
