name: Backend Continuous Deployment

on:
  push:
    paths:
      - 'starter/backend/**'
    branches:
      - main
  workflow_dispatch:

env: 
  WORKING_DIRECTORY: 'starter/backend'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Pipenv
      run: python -m pip install pipenv

    - name: Install flake8
      run: python -m pip install flake8

    - name: Install dependencies
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: pipenv install

    - name: Run lint
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: pipenv run lint

    - name: Run test
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: pipenv run test

  build-and-push:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: set SHORT_GITHUB_SHA
      id: set-short-sha
      run: echo "SHORT_GITHUB_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

    - name: Build and upload to ECR
      uses: ./.github/actions/build-and-upload-ecr
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
        working_directory: ${{ env.WORKING_DIRECTORY }}
        ecr_repository: backend
        image_tag: ${{ steps.set-short-sha.outputs.SHORT_GITHUB_SHA }}

  deploy:
    needs: [test, build-and-push]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Deploy to EKS
      uses: ./.github/actions/deploy-to-eks
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
        working_directory: ${{ env.WORKING_DIRECTORY }}
        cluster_name: cluster