name: Frontend CI

on:
  pull_request:
      paths:
      - 'starter/frontend/**'
      branches:
      - main
  workflow_dispatch:

env: 
  FRONTEND_PATH: 'starter/frontend'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Use Node.js 18

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('${{ env.FRONTEND_PATH }}/package-lock.json') }}

      - name: Install dependencies
        working-directory: ${{ env.FRONTEND_PATH }}
        run: npm ci

      - name: Run lint
        working-directory: ${{ env.FRONTEND_PATH }}
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Use Node.js 18

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('${{ env.FRONTEND_PATH }}/package-lock.json') }}

      - name: Install dependencies
        working-directory: ${{ env.FRONTEND_PATH }}
        run: npm ci

      - name: Run test
        working-directory: ${{ env.FRONTEND_PATH }}
        run: npm run test

  build:
    needs: [lint, test] # This job depends on the completion of 'lint' and 'test'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Restore cache
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('${{ env.FRONTEND_PATH }}/package-lock.json') }}

      - name: Install dependencies
        working-directory: ${{ env.FRONTEND_PATH }}
        run: npm ci

      - name: Build application
        working-directory: ${{ env.FRONTEND_PATH }}
        run: npm run build